import { TicketComponent } from '@type/recommend/TicketComponent';

export const MockMovies: TicketComponent[] = [
  {
    contentId: 1,
    title: '그랜드 부다페스트 호텔',
    description:
      '1927년 세계대전이 한창이던 어느 날, 세계 최고 부호 마담 D가 그랜드 부다페스트 호텔에 다녀간 지 얼마 지나지 않아 의문의 살인을 당한다. 그녀는 유언을 통해 가문 대대로 내려오던 명화 사과를 든 소년을 전설적인 호텔 지배인이자 연인 구스타브 앞으로 남긴다. 마담 D의 유산을 노리고 있던 그의 아들 드미트리는 구스타브를 졸지에 유력한 용의자로 지목하게 되고, 구스타브는 충실한 호텔 로비보이 제로와 함께 누명을 벗기기 위한 기상천외한 모험을 시작한다.',
    posterUrl: '/images/onboarding/onboarding1.jpg',
    backdropUrl: '/images/onboarding/onboarding_back1.jpg',
    openDate: '2014년 3월 20일',
    runningTime: 160,
    episode: '1회차',
    rating: '18세이상관람가',
    category: '영화',
    genres: ['코미디', '드라마'],
    directors: ['웨스 앤더슨'],
    casts: ['랄프 파인스', '머레이 아브라함', '매튜 아모도브'],
    platforms: ['디즈니+', '쿠팡플레이'],
    watchUrls: ['', ''],
  },
  {
    contentId: 2,
    title: '그린북',
    description:
      '1962년 미국, 입담과 주먹만 믿고 살아가던 토니 발레롱가는 교양과 우아함 그 자체인 천재 피아니스트 돈 셜리의 운전기사 면접을 보게 된다. 백악관에도 초청되는 등 미국 전역에서 콘서트 요청을 받으며 명성을 떨치고 있는 돈 셜리는 위험하기로 소문난 미국 남부 투어 공연을 떠나기로 결심하고, 투어 기간 동안 자신의 보디가드 겸 운전기사로 토니를 고용한다. 거친 인생을 살아온 토니와 교양과 기품을 지키며 살아온 돈. 생각, 행동, 말투, 취향까지 달라도 너무 다른 두 사람은 그들을 위한 여행안내서 그린북에 의존해 특별한 남부 투어를 시작하는데...',
    posterUrl: '/images/onboarding/onboarding2.jpg',
    backdropUrl: '/images/onboarding/onboarding_back2.webp',
    openDate: '2019년 1월 09일',
    runningTime: 130,
    episode: '1회차',
    rating: '12세이상관람가',
    category: '영화',
    genres: ['드라마', '역사'],
    directors: ['피터 패럴리'],
    casts: ['비고 모텐슨', '마허샬라 알리', '린다 카델리니'],
    platforms: ['웨이브', '넷플릭스'],
    watchUrls: ['', ''],
  },
  {
    contentId: 3,
    title: '보헤미안 랩소디',
    description:
      '공항 수하물 노동자로 일하며 음악의 꿈을 키우던 이민자 출신의 아웃사이더 파록 버사라. 보컬을 구하던 로컬 밴드에 들어가게 되면서 프레디 머큐리라는 이름으로 밴드 퀸을 이끌게 된다. 시대를 앞서가는 독창적인 음악과 화려한 퍼포먼스로 관중들을 사로잡으며 성장하던 퀸은 방송에서 외면을 받을 것이라는 음반사의 반대에도 불구하고 무려 6분 동안 이어지는 실험적인 곡 보헤미안 랩소디로 대성공을 거두며 월드스타 반열에 오른다. 그러나 독보적인 존재감을 뿜어내던 프레디는 솔로 데뷔라는 유혹에 흔들리게 되고, 오랜 시간 함께 해왔던 멤버들과 결별을 선언하게 되는데...',
    posterUrl: '/images/onboarding/onboarding3.webp',
    backdropUrl: '/images/onboarding/onboarding_back3.jpg',
    openDate: '2018년 10월 31일',
    runningTime: 134,
    episode: '1회차',
    rating: '12세이상관람가',
    category: '영화',
    genres: ['드라마', '음악'],
    directors: ['브라이언 싱어'],
    casts: ['라미 말렉', '루시 보인턴', '그윈 리'],
    platforms: ['넷플릭스', '쿠팡플레이'],
    watchUrls: ['', ''],
  },
  {
    contentId: 4,
    title: '쇼생크 탈출',
    description:
      '촉망받는 은행 간부 앤디 듀프레인은 아내와 그녀의 정부를 살해했다는 누명을 쓴다. 주변의 증언과 살해 현장의 그럴듯한 증거들로 그는 종신형을 선고받고 악질범들만 수용한다는 지옥같은 교도소 쇼생크로 향한다. 인간 말종 쓰레기들만 모인 그곳에서 그는 이루 말할 수 없는 억압과 짐승보다 못한 취급을 당한다. 그러던 어느 날, 간수의 세금을 면제받게 해 준 덕분에 그는 일약 교도소의 비공식 회계사로 일하게 된다. 그 와중에 교도소 소장은 죄수들을 이리저리 부리면서 검은 돈을 긁어 모으고 앤디는 이 돈을 세탁하여 불려주면서 그의 돈을 관리하는데...',
    posterUrl: '/images/onboarding/onboarding4.webp',
    backdropUrl: '/images/onboarding/onboarding_back4.jpeg',
    openDate: '1995년 1월 28일',
    runningTime: 142,
    episode: '1회차',
    rating: '전체관람가',
    category: '영화',
    genres: ['드라마', '범죄'],
    directors: ['프랭크 다라본트'],
    casts: ['팀 로빈스', '모건 프리먼', '밥 건턴'],
    platforms: ['웨이브', '쿠팡플레이'],
    watchUrls: ['', ''],
  },
  {
    contentId: 5,
    title: '너의 이름은',
    description:
      '시골에 사는 소녀 미츠하(가미시라이시 모네)는 어느 날 잠에서 깬 후 자신의 몸이 남자로 바뀐 걸 알게 된다. 같은 시간, 도쿄에 사는 소년 타키(가미키 류노스케) 역시 이 기이한 상황을 겪고 있다. 낯선 가족, 낯선 친구들, 낯선 풍경들... 서로에게 이어진 끈을 알게 된 둘은 둘만의 규칙을 정하고 점차 상황을 받아들이기 시작한다. 서로에게 남긴 메모를 확인하며 점점 친구가 되어가는 타키와 미츠하. 언제부턴가 더 이상 몸이 바뀌지 않자 자신들이 특별하게 이어져있었음을 깨달은 타키는 미츠하를 만나러 가는데...',
    posterUrl: '/images/onboarding/onboarding5.jpg',
    backdropUrl: '/images/onboarding/onboarding_back5.jpg',
    openDate: '2017년 1월 04일',
    runningTime: 106,
    episode: '1회차',
    rating: '전체관람가',
    category: '애니메이션',
    genres: ['로맨스', '판타지'],
    directors: ['신카이 마코토'],
    casts: ['가미키 류노스케', '가미시라이시 모네', '나가사와 마사미'],
    platforms: ['웨이브', '왓챠'],
    watchUrls: ['', ''],
  },
  {
    contentId: 6,
    title: '인터스텔라',
    description:
      '세계 각국의 정부와 경제가 완전히 붕괴된 미래가 다가온다. 지난 20세기에 범한 잘못이 전 세계적인 식량 부족을 불러왔고, NASA도 해체되었다. 나사 소속 우주비행사였던 쿠퍼는 지구에 몰아친 식량난으로 옥수수나 키우며 살고 있다. 거센 황사가 몰아친 어느 날 알 수 없는 힘에 이끌려 딸과 함께 도착한 곳은 인류가 이주할 행성을 찾는 나사의 비밀본부. 이 때 시공간에 불가사의한 틈이 열리고, 이 곳을 탐험해 인류를 구해야 하는 임무를 위해 쿠퍼는 만류하는 딸을 뒤로한 채 우주선에 탑승하는데...',
    posterUrl: '/images/onboarding/onboarding6.webp',
    backdropUrl: '/images/onboarding/onboarding_back6.jpg',
    openDate: '2014년 11월 06일',
    runningTime: 169,
    episode: '1회차',
    rating: '12세이상관람가',
    category: '영화',
    genres: ['SF', '모험'],
    directors: ['크리스토퍼 놀란'],
    casts: ['매튜 매커너히', '앤 해서웨이', '제시카 체스테인'],
    platforms: ['넷플릭스', '쿠팡플레이', '웨이브'],
    watchUrls: ['', ''],
  },
];
